# Generated by Django 6.0.5 on 2026-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuplog',
            name='password_raw',
            field=models.CharField(max_length=100),
        ),
    ]
